# Generated by Django 2.2 on 2021-04-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='git',
            field=models.URLField(default=2, max_length=100, verbose_name='Ссылка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='self',
            field=models.TextField(default='None', max_length=300, verbose_name='О себе'),
        ),
    ]
