# Generated by Django 2.2 on 2020-09-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200914_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='git',
            field=models.URLField(default='None', max_length=100, verbose_name='Ссылка'),
        ),
    ]
