# Generated by Django 2.2 on 2020-09-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200914_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='git',
            field=models.URLField(max_length=100, verbose_name='Ссылка'),
        ),
    ]
