# Generated by Django 2.2 on 2020-09-10 08:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_auto_20200910_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='author',
        ),
        migrations.RemoveField(
            model_name='project',
            name='author',
        ),
        migrations.AddField(
            model_name='issue',
            name='team',
            field=models.ManyToManyField(related_name='issue', to=settings.AUTH_USER_MODEL, verbose_name='Команда'),
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(related_name='project', to=settings.AUTH_USER_MODEL, verbose_name='Команда'),
        ),
    ]
